In [1]:
!pip install numpy

In [2]:
L=list(range(10))

In [3]:
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
type(L[0])

int

In [5]:
#list of string values
L2=[str(c)for c in L]

In [6]:
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [7]:
type(L2[0])

str

In [10]:
L3=[True, 2.0, 3, '4']
L3

[True, 2.0, 3, '4']

In [11]:
[type(item) for item in L3]

[bool, float, int, str]

In [13]:
#Fixed type arrays
import array

In [14]:
L=list(range(10))

In [15]:
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [16]:
A=array.array('i',L) # i refers to integers
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
import numpy as np

In [19]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [20]:
np.array([3.14, 2, 5,6]) #numpy upcasts data types if all elements of the array are not of same type

array([3.14, 2.  , 5.  , 6.  ])

In [21]:
np.array([3.15, 6, 7], dtype='float64')

array([3.15, 6.  , 7.  ])

In [23]:
np.array([range(i,i+3) for i in[2 ,4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [24]:
np.zeros(10, dtype= int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
np.ones(10, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [26]:
np.zeros(69)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0.])

In [29]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [30]:
np.full((3,5),69,dtype=int)

array([[69, 69, 69, 69, 69],
       [69, 69, 69, 69, 69],
       [69, 69, 69, 69, 69]])

In [31]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [32]:
np.linspace(0,1,69)

array([0.        , 0.01470588, 0.02941176, 0.04411765, 0.05882353,
       0.07352941, 0.08823529, 0.10294118, 0.11764706, 0.13235294,
       0.14705882, 0.16176471, 0.17647059, 0.19117647, 0.20588235,
       0.22058824, 0.23529412, 0.25      , 0.26470588, 0.27941176,
       0.29411765, 0.30882353, 0.32352941, 0.33823529, 0.35294118,
       0.36764706, 0.38235294, 0.39705882, 0.41176471, 0.42647059,
       0.44117647, 0.45588235, 0.47058824, 0.48529412, 0.5       ,
       0.51470588, 0.52941176, 0.54411765, 0.55882353, 0.57352941,
       0.58823529, 0.60294118, 0.61764706, 0.63235294, 0.64705882,
       0.66176471, 0.67647059, 0.69117647, 0.70588235, 0.72058824,
       0.73529412, 0.75      , 0.76470588, 0.77941176, 0.79411765,
       0.80882353, 0.82352941, 0.83823529, 0.85294118, 0.86764706,
       0.88235294, 0.89705882, 0.91176471, 0.92647059, 0.94117647,
       0.95588235, 0.97058824, 0.98529412, 1.        ])

In [33]:
np.random.random((3,4))

array([[0.83429592, 0.21775713, 0.25554783, 0.28533951],
       [0.75581212, 0.33202749, 0.8575925 , 0.00686246],
       [0.24239915, 0.7668733 , 0.82058257, 0.98668122]])

In [34]:
np.random.randint(0,70,(3,5))

array([[49, 16, 14, 45, 60],
       [47, 62, 11, 43, 57],
       [51, 55, 36, 51, 11]])

In [35]:
np.eye(4)# identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [36]:
np.empty(4)

array([1., 1., 1., 1.])

In [37]:
np.random.seed(0)

In [38]:
x1= np.random.randint(10, size=8)
x1

array([5, 0, 3, 3, 7, 9, 3, 5])

In [39]:
x2= np.random.randint(10, size=(2,3))
x2

array([[2, 4, 7],
       [6, 8, 8]])

In [40]:
x3 = np.random.randint(10, size=(2,3,4))

In [41]:
x3

array([[[1, 6, 7, 7],
        [8, 1, 5, 9],
        [8, 9, 4, 3]],

       [[0, 3, 5, 0],
        [2, 3, 8, 1],
        [3, 3, 3, 7]]])

In [42]:
x1[-1]

5

In [43]:
print(x3.ndim)

3


In [44]:
x1[0]=3.14

In [45]:
x1 #3.14 gets converted to integer as array takes only integer values

array([3, 0, 3, 3, 7, 9, 3, 5])

In [46]:
#Array slicing[start:stop:step]

In [47]:
#Reshaping of arrays

In [49]:
grid =np.arange(1,10).reshape((3,3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [51]:
grid.reshape((1,9))

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [52]:
grid.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [53]:
#Array concatenation and splitting

In [54]:
x=np.array([1,2,3])
y=np.array([4,5,6])
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [55]:
#vertically standing array

In [56]:
grid=np.array([[9,8,7],[4,5,6]])
np.vstack([x,grid])


array([[1, 2, 3],
       [9, 8, 7],
       [4, 5, 6]])